<?php

    $categoryUrl  = url('category');
    $clearCartUrl = url('cart/clear');
    echo <<<EOD
        <a href="{$categoryUrl}">Categories list</a>
        <br />
        <a href="{$clearCartUrl}">Clear you Cart</a>
        <br />
EOD;


MageLoader::start();

    $session = Mage::getSingleton('checkout/session');

    $output = "";
    foreach ($session->getQuote()->getAllItems() as $item) {
        $output .= 'SKU:   '. $item->getSku() . "<br>";
        $output .= 'name:  '. $item->getName() . "<br>";
        $output .= 'qty:   '. $item->getQty() . "<br>";
        $output .= 'price: '. $item->getBaseCalculationPrice() . "<br>";
        $output .= "</br>";
    }

    echo '<br />';
    echo '--------------------------------------------------------------------------------<br />';
    echo 'Cart <br />';
    echo '--------------------------------------------------------------------------------<br />';
    echo $output;

MageLoader::end();

