<?php



    $output = "";
    foreach ( MageSession::getCartItems() as $item ) {
        $output .= 'SKU:   '. $item['sku']   . "<br>";
        $output .= 'name:  '. $item['name']  . "<br>";
        $output .= 'qty:   '. $item['qty']   . "<br>";
        $output .= 'price: '. $item['price'] . "<br>";
        $output .= "</br>";
    }

    echo '<br />';
    echo '--------------------------------------------------------------------------------<br />';
    echo 'Cart <br />';
    echo '--------------------------------------------------------------------------------<br />';
    echo $output;



